// Code generated by ripple g, DO NOT EDIT.

package rpcclient

import (
	"sync"

	"github.com/bmbstack/ripple/fixtures/forum/proto"
)

var (
	studentClient     *proto.StudentClient
	studentClientOnce sync.Once

	teacherClient     *proto.TeacherClient
	teacherClientOnce sync.Once

	playerClient     *proto.PlayerClient
	playerClientOnce sync.Once
)

func GetStudentClient() *proto.StudentClient {
	studentClientOnce.Do(func() {
		closeStudentClient()
		studentClient = proto.NewStudentClient()
	})
	return studentClient
}

func closeStudentClient() {
	if studentClient != nil && studentClient.XClientPool != nil {
		studentClient.XClientPool.Close()
	}
}

func GetTeacherClient() *proto.TeacherClient {
	teacherClientOnce.Do(func() {
		closeTeacherClient()
		teacherClient = proto.NewTeacherClient()
	})
	return teacherClient
}

func closeTeacherClient() {
	if teacherClient != nil && teacherClient.XClientPool != nil {
		teacherClient.XClientPool.Close()
	}
}

func GetPlayerClient() *proto.PlayerClient {
	playerClientOnce.Do(func() {
		closePlayerClient()
		playerClient = proto.NewPlayerClient()
	})
	return playerClient
}

func closePlayerClient() {
	if playerClient != nil && playerClient.XClientPool != nil {
		playerClient.XClientPool.Close()
	}
}

func CloseAll() {
	closeStudentClient()
	closeTeacherClient()
	closePlayerClient()
}
