// Code generated by ripple g, DO NOT EDIT.

package rpcclient

import (
	"github.com/bmbstack/ripple/sync"

	"github.com/bmbstack/ripple/fixtures/forum/proto"
)

var (
	studentClient     *proto.StudentClient
	studentClientOnce sync.Once

	teacherClient     *proto.TeacherClient
	teacherClientOnce sync.Once

	playerClient     *proto.PlayerClient
	playerClientOnce sync.Once
)

func GetStudentClient() *proto.StudentClient {
	studentClientOnce.Do(func() {
		closeStudentClient()
		studentClient = proto.NewStudentClientMax(func() {
			studentClientOnce.Reset()
		})
	})
	return studentClient
}

func closeStudentClient() {
	if studentClient != nil {
		studentClient.Discovery.Close()
		studentClient.XClient.Close()
	}
}

func GetTeacherClient() *proto.TeacherClient {
	teacherClientOnce.Do(func() {
		closeTeacherClient()
		teacherClient = proto.NewTeacherClientMax(func() {
			teacherClientOnce.Reset()
		})
	})
	return teacherClient
}

func closeTeacherClient() {
	if teacherClient != nil {
		teacherClient.Discovery.Close()
		teacherClient.XClient.Close()
	}
}

func GetPlayerClient() *proto.PlayerClient {
	playerClientOnce.Do(func() {
		closePlayerClient()
		playerClient = proto.NewPlayerClientMax(func() {
			playerClientOnce.Reset()
		})
	})
	return playerClient
}

func closePlayerClient() {
	if playerClient != nil {
		playerClient.Discovery.Close()
		playerClient.XClient.Close()
	}
}

func CloseAll() {
	closeStudentClient()
	closeTeacherClient()
	closePlayerClient()
}
