// Code generated by ripple g, You can edit it again.
// source: protoc/testdata/proto/user.proto

package rpc

import (
	"context"
	"github.com/bmbstack/ripple/proto"
)

type UserRpc struct {
}

// GetInfo is server rpc method as defined
func (this *UserRpc) GetInfo(ctx context.Context, req *proto.GetInfoReq, reply *proto.GetInfoReply) (err error) {
	// TODO: add some code
	*reply = proto.GetInfoReply{}
	return nil
}
