// Code generated by ripple g, You can edit it again.
// source: proto/user.proto

package rpc

import (
	"context"
	"testdata/proto"
)

type UserRpc struct {
}

func (this *UserRpc) GetInfo(ctx context.Context, req *proto.GetInfoReq, reply *proto.GetInfoReply) (err error) {
	// TODO: add some code
	*reply = proto.GetInfoReply{}
	return nil
}
