// Code generated by ripple g, You can edit it again.
// source: no ref file, auto generate by component name

package services

import (
	"sync"
)

var (
	productService     *ProductService
	productServiceOnce sync.Once
)

// GetProductService 单例
func GetProductService() *ProductService {
	productServiceOnce.Do(func() {
		productService = &ProductService{}
	})
	return productService
}

type ProductService struct {
}
		