// Code generated by ripple g, DO NOT EDIT.

package services

import (
	"sync"

	"github.com/bmbstack/ripple/fixtures/forum/proto"
)

var (
	userClient     *proto.UserClient
	userClientOnce sync.Once

	orderClient     *proto.OrderClient
	orderClientOnce sync.Once

	studentClient     *proto.StudentClient
	studentClientOnce sync.Once
)

func GetUserClient() *proto.UserClient {
	userClientOnce.Do(func() {
		userClient = proto.NewUserClient()
	})
	return userClient
}

func GetOrderClient() *proto.OrderClient {
	orderClientOnce.Do(func() {
		orderClient = proto.NewOrderClient()
	})
	return orderClient
}

func GetStudentClient() *proto.StudentClient {
	studentClientOnce.Do(func() {
		studentClient = proto.NewStudentClient()
	})
	return studentClient
}
