// Code generated by ripple g, You can edit it again.
// source: fixtures/forum/internal/dto/student.dto.go

package services

import (
	"github.com/labstack/echo/v4"
	"sync"
)

var (
	studentService     *StudentService
	studentServiceOnce sync.Once
)

// GetStudentService 单例
func GetStudentService(ctx echo.Context) *StudentService {
	studentServiceOnce.Do(func() {
		studentService = &StudentService{}
	})
	studentService.ctx = ctx
	return studentService
}

type StudentService struct {
	ctx echo.Context
}
		