// Code generated by ripple g, You can edit it again.
// source: no ref file, auto generate by component name

package services

import (
	"sync"
)

var (
	studentService     *StudentService
	studentServiceOnce sync.Once
)

// GetStudentService 单例
func GetStudentService() *StudentService {
	studentServiceOnce.Do(func() {
		studentService = &StudentService{}
	})
	return studentService
}

type StudentService struct {
}
		