// Code generated by ripple g, You can edit it again.
// source: fixtures/forum/proto/player.proto

package rpc

import (
	"context"
	"github.com/bmbstack/ripple/fixtures/forum/proto"
)

type PlayerRpc struct {
}

// GetPlayerInfo is server rpc method as defined
func (this *PlayerRpc) GetPlayerInfo(ctx context.Context, req *proto.GetPlayerInfoReq, reply *proto.GetPlayerInfoResponse) (err error) {
	// TODO: add some code
	*reply = proto.GetPlayerInfoResponse{}
	return nil
}
