// Code generated by ripple g, You can edit it again.
// source: fixtures/forum/proto/student.proto

package rpc

import (
	"context"
	"github.com/bmbstack/ripple/fixtures/forum/proto"
)

type StudentRpc struct {
}

// Hello is server rpc method as defined
func (this *StudentRpc) Hello(ctx context.Context, req *proto.HelloReq, reply *proto.HelloReply) (err error) {
	// TODO: add some code
	*reply = proto.HelloReply{}
	return nil
}
