// Code generated by ripple g, You can edit it again.
// source: fixtures/forum/proto/student.proto

package rpc

import (
	"context"
	"github.com/bmbstack/ripple/fixtures/forum/proto"
)

type StudentRpc struct {
}

// Learn is server rpc method as defined
func (this *StudentRpc) Learn(ctx context.Context, req *proto.LearnReq, reply *proto.LearnReply) (err error) {
	// TODO: add some code
	*reply = proto.LearnReply{}
	reply.Name = "student learn function"
	return nil
}
