// Code generated by ripple g, You can edit it again.
// source: fixtures/forum/proto/teacher.proto

package rpc

import (
	"context"
	"github.com/bmbstack/ripple/fixtures/forum/proto"
)

type TeacherRpc struct {
}

// Teach is server rpc method as defined
func (this *TeacherRpc) Teach(ctx context.Context, req *proto.TeachReq, reply *proto.TeachReply) (err error) {
	// TODO: add some code
	*reply = proto.TeachReply{}
	reply.Name = "老师"
	return nil
}
