// Code generated by ripple g, You can edit it again.
// source: fixtures/forum/internal/dto/student.dto.go

package v1

import (
	"github.com/bmbstack/ripple/fixtures/forum/internal/dto"
	"github.com/bmbstack/ripple/fixtures/forum/internal/ecode"
	"github.com/labstack/echo/v4"
)

type StudentController struct {
	Group *echo.Group
	BaseController
}

func (this StudentController) Setup() {
	this.Group.POST("/student/learn", this.ActionStudentLearn)
	this.Group.POST("/student/hello", this.ActionStudentHello)
}

func (this StudentController) ActionStudentLearn(ctx echo.Context) error {
	params := &dto.ReqStudentLearn{}
	err := ctx.Bind(params)
	if err != nil {
		return ecode.Error(ctx, ecode.ParamError)
	}

	// TODO: add some code
	result := &dto.RespStudentLearn{}
	return ecode.OK(ctx, result)
}

func (this StudentController) ActionStudentHello(ctx echo.Context) error {
	params := &dto.ReqStudentHello{}
	err := ctx.Bind(params)
	if err != nil {
		return ecode.Error(ctx, ecode.ParamError)
	}

	// TODO: add some code
	result := &dto.RespStudentHello{}
	return ecode.OK(ctx, result)
}
