// Code generated by ripple g, You can edit it again.
// source: fixtures/forum/internal/dto/student.dto.go

package v1

import (
	"github.com/bmbstack/ripple/fixtures/forum/internal/dto"
	"github.com/bmbstack/ripple/fixtures/forum/internal/ecode"
	"github.com/labstack/echo/v4"
)

type StudentController struct {
	Group *echo.Group
	BaseController
}

func (this StudentController) Setup() {
	this.Group.POST("/student/say", this.ActionStudentSay)
	this.Group.POST("/student/hello", this.ActionHello)
}

func (this StudentController) ActionStudentSay(ctx echo.Context) error {
	params := &dto.ReqStudentSay{}
	err := ctx.Bind(params)
	if err != nil {
		return ecode.Error(ctx, ecode.ParamError)
	}

	// TODO: add some code
	result := &dto.RespStudentSay{}
	return ecode.OK(ctx, result)
}

func (this StudentController) ActionHello(ctx echo.Context) error {
	params := &dto.ReqHello{}
	err := ctx.Bind(params)
	if err != nil {
		return ecode.Error(ctx, ecode.ParamError)
	}

	// TODO: add some code
	result := &dto.RespHello{}
	return ecode.OK(ctx, result)
}
