// Code generated by ripple g, You can edit it again.
// source: fixtures/forum/internal/dto/teacher.dto.go

package v1

import (
	"github.com/bmbstack/ripple/fixtures/forum/internal/dto"
	"github.com/bmbstack/ripple/fixtures/forum/internal/ecode"
	"github.com/labstack/echo/v4"
)

type TeacherController struct {
	Group *echo.Group
	BaseController
}

func (this TeacherController) Setup() {
	this.Group.GET("/teacher/teach", this.ActionTeacherTeach)
	this.Group.POST("/teacher/hello", this.ActionTeacherHello)
}

func (this TeacherController) ActionTeacherTeach(ctx echo.Context) error {
	params := &dto.ReqTeacherTeach{}
	err := ctx.Bind(params)
	if err != nil {
		return ecode.Error(ctx, ecode.ParamError)
	}

	// TODO: add some code
	result := &dto.RespTeacherTeach{}
	return ecode.OK(ctx, result)
}

func (this TeacherController) ActionTeacherHello(ctx echo.Context) error {
	params := &dto.ReqTeacherHello{}
	err := ctx.Bind(params)
	if err != nil {
		return ecode.Error(ctx, ecode.ParamError)
	}

	// TODO: add some code
	result := &dto.RespTeacherHello{}
	return ecode.OK(ctx, result)
}
