// Code generated by ripple g, You can edit it again.
// source: fixtures/forum/internal/dto/user.dto.go

package v1

import (
	"github.com/bmbstack/ripple/fixtures/forum/internal/dto"
	"github.com/bmbstack/ripple/fixtures/forum/internal/ecode"
	"github.com/labstack/echo/v4"
)

type UserController struct {
	Group *echo.Group
	BaseController
}

func (this UserController) Setup() {
	this.Group.GET("/user/info", this.ActionUserInfo)
	this.Group.GET("/user/extra", this.ActionUserExtra)
	this.Group.POST("/user/say", this.ActionUserSay)
}

func (this UserController) ActionUserInfo(ctx echo.Context) error {
	params := &dto.ReqUserInfo{}
	err := ctx.Bind(params)
	if err != nil {
		return ecode.Error(ctx, ecode.ParamError)
	}

	// TODO: add some code
	result := &dto.RespUserInfo{}
	return ecode.OK(ctx, result)
}

func (this UserController) ActionUserExtra(ctx echo.Context) error {
	params := &dto.ReqUserExtra{}
	err := ctx.Bind(params)
	if err != nil {
		return ecode.Error(ctx, ecode.ParamError)
	}

	// TODO: add some code
	result := &dto.RespUserExtra{}
	return ecode.OK(ctx, result)
}

func (this UserController) ActionUserSay(ctx echo.Context) error {
	params := &dto.ReqUserSay{}
	err := ctx.Bind(params)
	if err != nil {
		return ecode.Error(ctx, ecode.ParamError)
	}

	// TODO: add some code
	result := &dto.RespUserSay{}
	return ecode.OK(ctx, result)
}
